name: iProtector
main: LDX\iProtector\Main
author: LDX
version: "2.1"
load: POSTWORLD
api: [1.6.0]
commands:
  area:
    description: "Allows you to manage areas."
    usage: "/area <pos1/pos2/create/list/flag/delete>"
    permission: iprotector.command.area
permissions:
  iprotector:
    description: "Allows access to all iProtector features."
    default: false
    children:
      iprotector.access:
        description: "Allows access to editing terrain in iProtector areas."
        default: op
      iprotector.command:
        description: "Allows access to all iProtector commands."
        default: false
        children:
          iprotector.command.area:
            description: "Allows access to the area command."
            default: op
            children:
              iprotector.command.area.pos1:
                description: "Allows access to the iProtector pos1 subcommand."
                default: op
              iprotector.command.area.pos2:
                description: "Allows access to the iProtector pos2 subcommand."
                default: op
              iprotector.command.area.create:
                description: "Allows access to the iProtector create subcommand."
                default: op
              iprotector.command.area.list:
                description: "Allows access to the iProtector list subcommand."
                default: op
              iprotector.command.area.flag:
                description: "Allows access to the iProtector flag subcommand."
                default: op
              iprotector.command.area.delete:
                description: "Allows access to the iProtector delete subcommand."
                default: op
